export const USER_FETCH_REQUESTED = "users/USER_FETCH_REQUESTED"
export const USER_FETCH_SUCCEEDED = "users/USER_FETCH_SUCCEEDED"
export const USER_FETCH_FAILED = "users/USER_FETCH_FAILED"
export const USER_FETCH_LOADING = "users/USER_FETCH_LOADING"
